### ISSUE TITLE
Issue #1

### ISSUE THREAD

**Issue by PRASHIKGITHUB** [PRASHIKGITHUB/Amazon-s-Clone#1]
Instead of giving border to navbar elements, make changes such that it will change colour to **orange** while hovering.
![isssue1]([https://github.com/PRASHIKGITHUB/Amazon-s-Clone/assets/96679240/a1636330-c349-4bc2-a7da-e609fd8f5061])

**Comment by shivshankar001** [comment]
#1 solved please verify the merge request

**Comment by PRASHIKGITHUB** [comment]
it has been solved!
